[versions]
detekt = "1.23.8"
kotlin = "2.3.10"
ktlintGradle = "13.1.0"
pluginPublish = "1.3.1"
versionCheck = "0.53.0"
compose = "1.10.1"
agp = "8.10.1"
downloadTask = "5.6.0"
kotlinPoet = "2.1.0"
batik = "1.19"
vanniktechMavenPublish = "0.36.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish"}
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose"}

[libraries]
junit = "junit:junit:4.13.2"
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
agp-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
download-task = { module = "de.undercouch:gradle-download-task", version.ref = "downloadTask" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
batik-transcoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batik" }
